spring:
  profiles:
    #active: local, redis
    active: local, local cache
  data:
    redis:
      host: 127.0.0.1
      port: 6379



---
# DATABASE
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/sbb
    driver-class-name: org.postgresql.Driver
    username: web
    password: web
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      #       ddl-auto: create
      ddl-auto: update

jwt:
  issuer: dustin
  subject: dustinsprc
  # 초단위 3600 -> 1시간
  #expired-at: 3600
  expired-at: 60
  secret: dutinssecurityprc
  prefix: Bearer

server:
  error:
    whitelabel:
      enabled: false
  port: 8881

