# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sbb
    driver-class-name: org.postgresql.Driver
    username: web
    password: web
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

rigo:
  node:
    url: http://192.168.252.60:26657/